version: '3'

services:
  nestjs-deploy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 37020:3000
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app

networks:
  nestjs-network:
    driver: bridge
