version: '3'

services:
  mongo:
    hostname: ${MONGO_HOST}
    container_name: mongo
    image: mongo:latest
    env_file:
      - ./.env
    volumes:
      - ${MONGO_DB_PATH}:/data/db
      - ./replica.key:/data/replica.key
    ports:
      - ${MONGO_PORT}:27017
    restart: always
    command: bash -c "chmod 400 /data/replica.key && mongod --bind_ip_all --replSet rs0 --keyFile /data/replica.key"

  mongo-init:
    depends_on:
      - mongo
    restart: on-failure
    image: mongo:latest
    container_name: mongo-init
    entrypoint: ['bash', '/scripts/init-rs.sh']
    env_file:
      - ./.env
    volumes:
      - ./init.sh:/scripts/init-rs.sh
